image: nanobox/base

stages:
  - install
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - dev
  script:
    - echo Building nanobox image
    - nanobox build

test:
  stage: test
  only:
    - dev
  script:
    - echo Running tests
    - nanobox run npm test
  allow_failure: true

deploy:
  stage: deploy
  only:
    - dev
  script:
    - echo Deploying application
    - nanobox deploy

