image: node:latest

stages:
  - build_express
  - build_react
  - react_tests

cache:
  paths:
    - node_modules/
    - client/node_modules/

test_build_express:
  stage: build_express
  script:
    - npm install

test_build_react:
  stage: build_react
  script:
    - cd client/
    - npm install
    - ./node_modules/.bin/node-sass src/scss -o src/css --output-style compressed 

react_unit_tests:
  stage: react_tests
  script:
    - cd client/
    - npm install
    - ./node_modules/.bin/node-sass src/scss -o src/css --output-style compressed
    - npm test
