image: ubuntu:trusty

stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - dev
  script:
    - echo Installing nanobox
    - sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"
    - echo Building nanobox image
    - nanobox build

test:
  stage: test
  only:
    - dev
  script:
    - echo Installing nanobox
    - sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"
    - echo Running tests
    - nanobox run npm test
  allow_failure: true

deploy:
  stage: deploy
  only:
    - dev
  script:
    - echo Installing nanobox
    - sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"
    - echo Deploying application
    - nanobox deploy

