image: node:latest

stages:
  - install
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/
    - client/node_modules/

install:
  stage: install
  only:
    - dev
  script:
    - echo Installing nanobox
    - sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"

build:
  stage: build
  only:
    - dev
  script:
    - echo Building nanobox image
    - nanobox build

test:
  stage: test
  only:
    - dev
  script:
    - echo Running tests
    - nanobox run npm test

deploy:
  stage: deploy
  only:
    - dev
  script:
    - echo Deploying application
    - nanobox deploy
