image: node:latest

stages:
  - build_express
  - build_react
  - express_tests
  - react_tests
  - lint
 
cache:
  paths:
    - node_modules/
    - client/node_modules/

test_build_express:
  stage: build_express
  script:
    - npm install

test_build_react:
  stage: build_react
  script:
    - cd client/
    - npm install
    - ./node_modules/.bin/node-sass src/scss -o src/css --output-style compressed 

express_unit_tests:
  stage: express_tests
  script:
    - npm install
    - npm test

react_unit_tests:
  stage: react_tests
  script:
    - cd client/
    - npm install
    - ./node_modules/.bin/node-sass src/scss -o src/css --output-style compressed
    - npm test -- --coverage
    - echo "Job done."

eslint:
  stage: lint
  script:
    - npm install -g eslint
    - eslint 'routes/associations.js'