#safelist
branches:
  only:
    - master
    - develop

dist: trusty
sudo: required
language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
    - "client/node_modules"

services:
  - postgresql

before_script:
  - psql -c 'create database mygrant_test;' -U postgres

install: sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"

jobs:
  include:
    - stage: test
      script: nanobox run npm test
      if: branch IN (develop, master)

deploy: 
    provider: script
    script: bash scripts/deploy.sh $TRAVIS_BRANCH
    on:
      all_branches: true
