dist: trusty
sudo: required
language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
    - "client/node_modules"

before_install:
  - "cd client/ && npm install && cd .."

install: sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"

jobs:
  include:
    - stage: test
      script: npm test
      if: branch IN (develop, master)
    - stage: deploy-dev
      if: branch = develop
      script: 
        - nanobox remote add mygrant-dev
        - nanobox deploy
    - stage: deploy-master
      if: branch = master
      script:
        - nanobox remote add mygrant
        - nanobox deploy
